sudo: false
language: go
go:
  - "1.10"

cache:
 # https://github.com/golang/dep/blob/2def43184ada5ecd015a24fde5b5ece169d38c5a/docs/FAQ.md#how-do-i-use-dep-in-ci
  directories:
    - $GOPATH/pkg/dep

install:
  - make setup
script:
  - make
  - make test

# build PRs, and master branch, but not every other branch as well
# https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-160820262
branches:
  only:
    master
